[package]
name = "pray-server"
version = "1.0.3"
edition = "2021"

[dependencies]
clap = { version = "4.2.1", default-features = false, features = ["cargo", "derive", "env", "std"] }
crossbeam-utils = "0.8.15"
png = "0.17.7"
show-image = "0.13.1"
